### ISSUE TITLE
pluggable schema/collection framework

### ISSUE THREAD

**Issue by michael-conway** [NIEHS/accelerator-core#9]
Add ability to configure type, schema, collection matrix. This allows multiple document types to flow through the accel pipeline.

A .yaml configuration file can be created like this:

```yaml

types:
- name: pcor
  schema: pcor
  collection: pcor
  temp_collection: pcor_temp
- name: accelerator
  schema: accel-schema
  collection: pcor
  temp_collection: pcor_temp




```

This will be used to resolve validation and collection in the ingest and dissemination
